"""Curated seed registry for topic-driven source discovery.

Seeds are identity and ranking hints only. They never schedule fetches,
create subscriptions, or qualify as Claim evidence.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from app.services.source_catalog import SourceKind


class DiscoveryProvenance(StrEnum):
    CURATED_SEED = "curated_seed"
    REPOSITORY_METADATA = "repository_metadata"
    WEBSITE_FEED = "website_feed"
    STATUSPAGE_LINK = "statuspage_link"
    SITEMAP_LINK = "sitemap_link"
    PACKAGE_HOMEPAGE = "package_homepage"
    EXTERNAL_INDEX = "external_index"


@dataclass(frozen=True)
class SourceSeed:
    publisher_slug: str
    publisher_name: str
    homepage_url: str
    url: str
    family: SourceKind
    concept_ids: tuple[str, ...]
    provenance: str
    display_name: str
    why: str
    aliases: tuple[str, ...] = ()
    repository: str | None = None
    package: str | None = None


def _seed(
    *,
    slug: str,
    name: str,
    home: str,
    url: str,
    family: SourceKind,
    concepts: tuple[str, ...],
    provenance: str,
    display: str,
    why: str,
    aliases: tuple[str, ...] = (),
    repository: str | None = None,
    package: str | None = None,
) -> SourceSeed:
    return SourceSeed(
        publisher_slug=slug,
        publisher_name=name,
        homepage_url=home,
        url=url,
        family=family,
        concept_ids=concepts,
        provenance=provenance,
        display_name=display,
        why=why,
        aliases=aliases,
        repository=repository,
        package=package,
    )


def _rss_seed(
    *,
    slug: str,
    name: str,
    home: str,
    url: str,
    concepts: tuple[str, ...],
    display: str,
    why: str,
    aliases: tuple[str, ...] = (),
) -> SourceSeed:
    return _seed(
        slug=slug,
        name=name,
        home=home,
        url=url,
        family=SourceKind.RSS_ATOM,
        concepts=concepts,
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display=display,
        why=why,
        aliases=aliases,
    )


CURATED_SOURCE_SEEDS: tuple[SourceSeed, ...] = (
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://github.com/facebook/react/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("react",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="React GitHub Releases",
        why="Official repository releases for React",
        aliases=("https://github.com/facebook/react",),
        repository="facebook/react",
    ),
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://react.dev/blog/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("react",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="React blog feed",
        why="Official React blog RSS",
    ),
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://react.dev/learn",
        family=SourceKind.GENERIC_WEB,
        concepts=("react",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="React documentation",
        why="Official React documentation",
    ),
    _seed(
        slug="llvm",
        name="LLVM",
        home="https://llvm.org",
        url="https://github.com/llvm/llvm-project/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("llvm", "llvm-scalar-evolution", "compiler-optimization"),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="LLVM project releases",
        why="Official LLVM repository releases",
        repository="llvm/llvm-project",
    ),
    _seed(
        slug="llvm",
        name="LLVM",
        home="https://llvm.org",
        url="https://blog.llvm.org/index.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("llvm", "llvm-scalar-evolution", "compiler-optimization"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="LLVM blog feed",
        why="Official LLVM blog RSS",
    ),
    _seed(
        slug="llvm",
        name="LLVM",
        home="https://llvm.org",
        url="https://llvm.org/docs/",
        family=SourceKind.GENERIC_WEB,
        concepts=("llvm", "llvm-scalar-evolution", "compiler-optimization"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="LLVM documentation",
        why="Official LLVM documentation, including Scalar Evolution",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://github.com/python/cpython/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("python",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="CPython releases",
        why="Official CPython repository releases",
        repository="python/cpython",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://blog.python.org/feeds/posts/default",
        family=SourceKind.RSS_ATOM,
        concepts=("python",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Python blog feed",
        why="Official Python blog Atom feed",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://docs.python.org/3/",
        family=SourceKind.GENERIC_WEB,
        concepts=("python",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Python documentation",
        why="Official Python language documentation",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://github.com/fastapi/fastapi/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="FastAPI releases",
        why="Official FastAPI repository releases",
        aliases=("https://github.com/encode/fastapi/releases",),
        repository="fastapi/fastapi",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://pypi.org/project/fastapi/",
        family=SourceKind.GENERIC_WEB,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.PACKAGE_HOMEPAGE,
        display="FastAPI on PyPI",
        why="Package registry homepage for FastAPI",
        package="fastapi",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://fastapi.tiangolo.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="FastAPI documentation",
        why="Official FastAPI documentation",
    ),
    _seed(
        slug="kubernetes",
        name="Kubernetes",
        home="https://kubernetes.io",
        url="https://github.com/kubernetes/kubernetes/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("kubernetes",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Kubernetes releases",
        why="Official Kubernetes repository releases",
        repository="kubernetes/kubernetes",
    ),
    _seed(
        slug="kubernetes",
        name="Kubernetes",
        home="https://kubernetes.io",
        url="https://kubernetes.io/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("kubernetes",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Kubernetes blog feed",
        why="Official Kubernetes website feed",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://github.blog/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("github", "github-actions"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="GitHub blog feed",
        why="Official GitHub blog RSS",
        aliases=("https://www.github.com",),
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://kctbh9vrtdwd.statuspage.io/api/v2/summary.json",
        family=SourceKind.STATUSPAGE,
        concepts=("github", "github-actions"),
        provenance=DiscoveryProvenance.STATUSPAGE_LINK,
        display="GitHub Statuspage",
        why="Known official GitHub Statuspage",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://api.github.com",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("github",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="GitHub Releases API",
        why="Official GitHub Releases API",
    ),
    _seed(
        slug="osv",
        name="OSV",
        home="https://osv.dev",
        url="https://api.osv.dev/v1/query",
        family=SourceKind.OSV,
        concepts=("security", "cve"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="OSV vulnerability API",
        why="Official OSV query API for security advisories",
    ),
    _seed(
        slug="cisa",
        name="CISA Cybersecurity Advisories",
        home="https://www.cisa.gov",
        url="https://www.cisa.gov/news-events/cybersecurity-advisories",
        family=SourceKind.GENERIC_WEB,
        concepts=("security", "cve"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="CISA Cybersecurity Advisories",
        why="Official CISA cybersecurity advisories",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://api.github.com/advisories",
        family=SourceKind.GITHUB_ADVISORY,
        concepts=("security", "cve", "github"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="GitHub Advisory Database",
        why="Official GitHub security advisories",
    ),
    _seed(
        slug="kotlin",
        name="Kotlin",
        home="https://kotlinlang.org",
        url="https://github.com/JetBrains/kotlin/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("kotlin",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Kotlin releases",
        why="Official Kotlin repository releases",
        repository="JetBrains/kotlin",
    ),
    _seed(
        slug="kotlin",
        name="Kotlin",
        home="https://kotlinlang.org",
        url="https://blog.jetbrains.com/kotlin/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("kotlin",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Kotlin blog feed",
        why="Official Kotlin blog RSS",
    ),
    _seed(
        slug="android",
        name="Android",
        home="https://developer.android.com",
        url="https://android-developers.googleblog.com/feeds/posts/default",
        family=SourceKind.RSS_ATOM,
        concepts=("android", "kotlin"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Android Developers blog feed",
        why="Official Android Developers blog feed",
    ),
    _seed(
        slug="android",
        name="Android",
        home="https://developer.android.com",
        url="https://developer.android.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("android",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Android developer documentation",
        why="Official Android developer documentation",
    ),
    _seed(
        slug="flutter",
        name="Flutter",
        home="https://flutter.dev",
        url="https://github.com/flutter/flutter/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("flutter",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Flutter releases",
        why="Official Flutter repository releases",
        repository="flutter/flutter",
    ),
    _seed(
        slug="flutter",
        name="Flutter",
        home="https://flutter.dev",
        url="https://flutter.dev/blog/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("flutter",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Flutter blog feed",
        why="Official Flutter blog feed",
    ),
    _seed(
        slug="cloudflare-workers",
        name="Cloudflare Workers",
        home="https://developers.cloudflare.com/workers/",
        url="https://blog.cloudflare.com/rss/",
        family=SourceKind.RSS_ATOM,
        concepts=("cloudflare-workers", "cloudflare"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Cloudflare blog feed",
        why="Official Cloudflare blog RSS covering Workers",
    ),
    _seed(
        slug="cloudflare-workers",
        name="Cloudflare Workers",
        home="https://developers.cloudflare.com/workers/",
        url="https://developers.cloudflare.com/workers/",
        family=SourceKind.GENERIC_WEB,
        concepts=("cloudflare-workers", "cloudflare"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Cloudflare Workers documentation",
        why="Official Cloudflare Workers documentation",
    ),
    _seed(
        slug="openai",
        name="OpenAI",
        home="https://openai.com",
        url="https://openai.com/news/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("openai-api", "openai"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="OpenAI news feed",
        why="Official OpenAI news RSS",
    ),
    _seed(
        slug="openai",
        name="OpenAI",
        home="https://openai.com",
        url="https://platform.openai.com/docs",
        family=SourceKind.GENERIC_WEB,
        concepts=("openai-api",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="OpenAI API documentation",
        why="Official OpenAI API documentation",
    ),
    _seed(
        slug="nextjs",
        name="Next.js",
        home="https://nextjs.org",
        url="https://github.com/vercel/next.js/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("nextjs",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Next.js releases",
        why="Official Next.js repository releases",
        repository="vercel/next.js",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://github.com/rust-lang/rust/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("rust",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Rust releases",
        why="Official Rust repository releases",
        repository="rust-lang/rust",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://blog.rust-lang.org/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("rust",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Rust blog feed",
        why="Official Rust blog RSS",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://this-week-in-rust.org/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("rust",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="This Week in Rust",
        why="Weekly Rust community digest RSS",
    ),
    _seed(
        slug="hugo",
        name="Hugo",
        home="https://gohugo.io",
        url="https://gohugo.io/index.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("hugo",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Hugo docs feed",
        why="Official Hugo documentation RSS",
    ),
    _seed(
        slug="jekyll",
        name="Jekyll",
        home="https://jekyllrb.com",
        url="https://jekyllrb.com/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("jekyll",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Jekyll blog feed",
        why="Official Jekyll blog RSS",
    ),
    _seed(
        slug="ghost",
        name="Ghost",
        home="https://ghost.org",
        url="https://ghost.org/changelog/rss/",
        family=SourceKind.RSS_ATOM,
        concepts=("ghost",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Ghost changelog feed",
        why="Official Ghost changelog RSS",
    ),
)

CURATED_SUBSCRIPTION_FEED_SEEDS: tuple[SourceSeed, ...] = (
    # Additional official RSS/Atom feeds verified against public endpoints.
    _rss_seed(
        slug="react-native",
        name="React Native",
        home="https://reactnative.dev",
        url="https://reactnative.dev/blog/rss.xml",
        concepts=("react-native", "react"),
        display="React Native blog feed",
        why="Official React Native blog RSS",
    ),
    _rss_seed(
        slug="nextjs",
        name="Next.js",
        home="https://nextjs.org",
        url="https://nextjs.org/feed.xml",
        concepts=("nextjs", "react", "typescript"),
        display="Next.js blog feed",
        why="Official Next.js blog RSS",
    ),
    _rss_seed(
        slug="go",
        name="Go",
        home="https://go.dev",
        url="https://go.dev/blog/feed.atom",
        concepts=("go",),
        display="Go blog feed",
        why="Official Go programming language blog Atom feed",
    ),
    _rss_seed(
        slug="swift",
        name="Swift",
        home="https://www.swift.org",
        url="https://www.swift.org/atom.xml",
        concepts=("swift", "ios"),
        display="Swift blog feed",
        why="Official Swift project Atom feed",
    ),
    _rss_seed(
        slug="ruby",
        name="Ruby",
        home="https://www.ruby-lang.org",
        url="https://www.ruby-lang.org/en/feeds/news.rss",
        concepts=("ruby",),
        display="Ruby news feed",
        why="Official Ruby language news RSS",
    ),
    _rss_seed(
        slug="rails",
        name="Ruby on Rails",
        home="https://rubyonrails.org",
        url="https://rubyonrails.org/feed.xml",
        concepts=("rails", "ruby"),
        display="Ruby on Rails feed",
        why="Official Ruby on Rails project feed",
    ),
    _rss_seed(
        slug="django",
        name="Django",
        home="https://www.djangoproject.com",
        url="https://www.djangoproject.com/rss/weblog/",
        concepts=("django", "python"),
        display="Django weblog feed",
        why="Official Django project weblog RSS",
    ),
    _rss_seed(
        slug="typescript",
        name="TypeScript",
        home="https://www.typescriptlang.org",
        url="https://devblogs.microsoft.com/typescript/feed/",
        concepts=("typescript", "javascript"),
        display="TypeScript blog feed",
        why="Official TypeScript team blog RSS",
    ),
    _rss_seed(
        slug="mdn",
        name="MDN Web Docs",
        home="https://developer.mozilla.org",
        url="https://developer.mozilla.org/en-US/blog/rss.xml",
        concepts=("javascript", "webassembly"),
        display="MDN Web Docs blog feed",
        why="Official MDN Web Docs blog RSS",
    ),
    _rss_seed(
        slug="webassembly",
        name="WebAssembly",
        home="https://webassembly.org",
        url="https://webassembly.org/feed.xml",
        concepts=("webassembly",),
        display="WebAssembly blog feed",
        why="Official WebAssembly project feed",
    ),
    _rss_seed(
        slug="helm",
        name="Helm",
        home="https://helm.sh",
        url="https://helm.sh/blog/index.xml",
        concepts=("helm", "kubernetes"),
        display="Helm blog feed",
        why="Official Helm project feed",
    ),
    _rss_seed(
        slug="gitlab",
        name="GitLab",
        home="https://about.gitlab.com",
        url="https://about.gitlab.com/atom.xml",
        concepts=("gitlab",),
        display="GitLab blog feed",
        why="Official GitLab blog Atom feed",
    ),
    _rss_seed(
        slug="gitlab",
        name="GitLab",
        home="https://docs.gitlab.com",
        url="https://docs.gitlab.com/releases/all-releases.xml",
        concepts=("gitlab",),
        display="GitLab release feed",
        why="Official GitLab release notes RSS",
    ),
    _rss_seed(
        slug="graphql",
        name="GraphQL",
        home="https://graphql.org",
        url="https://graphql.org/blog/rss.xml",
        concepts=("graphql",),
        display="GraphQL blog feed",
        why="Official GraphQL Foundation blog feed",
    ),
    _rss_seed(
        slug="grpc",
        name="gRPC",
        home="https://grpc.io",
        url="https://grpc.io/blog/index.xml",
        concepts=("grpc",),
        display="gRPC blog feed",
        why="Official gRPC project feed",
    ),
    _rss_seed(
        slug="apollo",
        name="Apollo GraphQL",
        home="https://www.apollographql.com",
        url="https://www.apollographql.com/blog/rss.xml",
        concepts=("apollo", "apollo-graphql", "graphql"),
        display="Apollo blog feed",
        why="Official Apollo GraphQL blog RSS",
    ),
    _rss_seed(
        slug="aws",
        name="AWS",
        home="https://aws.amazon.com",
        url="https://aws.amazon.com/blogs/aws/feed/",
        concepts=("aws",),
        display="AWS News Blog feed",
        why="Official AWS News Blog RSS",
    ),
    _rss_seed(
        slug="aws",
        name="AWS",
        home="https://aws.amazon.com",
        url="https://aws.amazon.com/about-aws/whats-new/recent/feed/",
        concepts=("aws",),
        display="AWS What's New feed",
        why="Official AWS What's New RSS",
    ),
    _rss_seed(
        slug="aws",
        name="AWS",
        home="https://aws.amazon.com",
        url="https://aws.amazon.com/blogs/compute/feed/",
        concepts=("aws",),
        display="AWS Compute Blog feed",
        why="Official AWS Compute Blog RSS",
    ),
    _rss_seed(
        slug="cloudflare-workers",
        name="Cloudflare Workers",
        home="https://developers.cloudflare.com/workers/",
        url="https://developers.cloudflare.com/changelog/rss/index.xml",
        concepts=("cloudflare-workers", "cloudflare"),
        display="Cloudflare changelog feed",
        why="Official Cloudflare developer changelog RSS",
    ),
    _rss_seed(
        slug="kubernetes",
        name="Kubernetes",
        home="https://kubernetes.io",
        url="https://kubernetes.io/docs/reference/issues-security/official-cve-feed/feed.xml",
        concepts=("kubernetes", "security", "cve"),
        display="Kubernetes security feed",
        why="Official Kubernetes CVE RSS feed",
    ),
    _rss_seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://github.blog/changelog/feed/",
        concepts=("github", "github-actions"),
        display="GitHub Changelog feed",
        why="Official GitHub Changelog RSS",
    ),
    _rss_seed(
        slug="postgresql",
        name="PostgreSQL",
        home="https://www.postgresql.org",
        url="https://www.postgresql.org/versions.rss",
        concepts=("postgresql",),
        display="PostgreSQL versions feed",
        why="Official PostgreSQL version release RSS",
    ),
    _rss_seed(
        slug="mongodb",
        name="MongoDB",
        home="https://www.mongodb.com",
        url="https://www.mongodb.com/products/updates/rss",
        concepts=("mongodb",),
        display="MongoDB product updates feed",
        why="Official MongoDB product updates RSS",
    ),
    _rss_seed(
        slug="redis",
        name="Redis",
        home="https://redis.io",
        url="https://redis.io/blog/feed/",
        concepts=("redis",),
        display="Redis blog feed",
        why="Official Redis blog RSS",
    ),
    _rss_seed(
        slug="elasticsearch",
        name="Elasticsearch",
        home="https://www.elastic.co",
        url="https://www.elastic.co/blog/feed",
        concepts=("elasticsearch",),
        display="Elastic blog feed",
        why="Official Elastic blog feed",
    ),
    _rss_seed(
        slug="opentelemetry",
        name="OpenTelemetry",
        home="https://opentelemetry.io",
        url="https://opentelemetry.io/blog/index.xml",
        concepts=("opentelemetry",),
        display="OpenTelemetry blog feed",
        why="Official OpenTelemetry project feed",
    ),
    _rss_seed(
        slug="prometheus",
        name="Prometheus",
        home="https://prometheus.io",
        url="https://prometheus.io/blog/feed.xml",
        concepts=("prometheus",),
        display="Prometheus blog feed",
        why="Official Prometheus project feed",
    ),
    _rss_seed(
        slug="grafana",
        name="Grafana",
        home="https://grafana.com",
        url="https://grafana.com/blog/index.xml",
        concepts=("grafana",),
        display="Grafana Labs blog feed",
        why="Official Grafana Labs blog feed",
    ),
    _rss_seed(
        slug="datadog",
        name="Datadog",
        home="https://www.datadoghq.com",
        url="https://www.datadoghq.com/blog/index.xml",
        concepts=("datadog",),
        display="Datadog blog feed",
        why="Official Datadog blog feed",
    ),
    _rss_seed(
        slug="tensorflow",
        name="TensorFlow",
        home="https://www.tensorflow.org",
        url="https://blog.tensorflow.org/feeds/posts/default",
        concepts=("tensorflow", "python"),
        display="TensorFlow blog feed",
        why="Official TensorFlow blog Atom feed",
    ),
    _rss_seed(
        slug="huggingface",
        name="Hugging Face",
        home="https://huggingface.co",
        url="https://huggingface.co/blog/feed.xml",
        concepts=("huggingface", "hugging-face"),
        display="Hugging Face blog feed",
        why="Official Hugging Face blog RSS",
    ),
    _rss_seed(
        slug="langchain",
        name="LangChain",
        home="https://www.langchain.com",
        url="https://www.langchain.com/blog/rss.xml",
        concepts=("langchain",),
        display="LangChain blog feed",
        why="Official LangChain blog RSS",
    ),
    _rss_seed(
        slug="stripe",
        name="Stripe",
        home="https://stripe.com",
        url="https://stripe.com/blog/feed.rss",
        concepts=("stripe",),
        display="Stripe blog feed",
        why="Official Stripe blog RSS",
    ),
    _rss_seed(
        slug="twilio",
        name="Twilio",
        home="https://www.twilio.com",
        url="https://www.twilio.com/en-us/blog.feed.xml",
        concepts=("twilio",),
        display="Twilio blog feed",
        why="Official Twilio blog feed",
    ),
    _rss_seed(
        slug="auth0",
        name="Auth0",
        home="https://auth0.com",
        url="https://auth0.com/blog/rss.xml",
        concepts=("auth0",),
        display="Auth0 blog feed",
        why="Official Auth0 blog RSS",
    ),
    _rss_seed(
        slug="apple",
        name="Apple",
        home="https://www.apple.com",
        url="https://www.apple.com/newsroom/rss-feed.rss",
        concepts=("company-apple", "apple", "ios", "swift"),
        display="Apple Newsroom feed",
        why="Official Apple Newsroom RSS",
    ),
    _rss_seed(
        slug="google",
        name="Google",
        home="https://blog.google",
        url="https://blog.google/rss/",
        concepts=("company-google", "google", "android"),
        display="Google blog feed",
        why="Official Google blog feed",
    ),
    _rss_seed(
        slug="microsoft",
        name="Microsoft",
        home="https://blogs.microsoft.com",
        url="https://blogs.microsoft.com/feed/",
        concepts=("company-microsoft", "microsoft", "microsoft-azure", "typescript"),
        display="Microsoft Stories feed",
        why="Official Microsoft corporate blog RSS",
    ),
    _rss_seed(
        slug="meta",
        name="Meta",
        home="https://about.fb.com",
        url="https://about.fb.com/news/feed/",
        concepts=("company-meta", "meta"),
        display="Meta Newsroom feed",
        why="Official Meta Newsroom RSS",
    ),
    _rss_seed(
        slug="inside-java",
        name="Inside Java",
        home="https://inside.java",
        url="https://inside.java/feed.xml",
        concepts=("java",),
        display="Inside Java feed",
        why="Official Java team blog feed",
    ),
    _rss_seed(
        slug="jetbrains",
        name="JetBrains",
        home="https://www.jetbrains.com",
        url="https://blog.jetbrains.com/feed/",
        concepts=("jetbrains", "kotlin", "java", "python", "javascript"),
        display="JetBrains blog feed",
        why="Official JetBrains combined blog RSS",
    ),
    _rss_seed(
        slug="jetbrains-idea",
        name="IntelliJ IDEA",
        home="https://www.jetbrains.com/idea/",
        url="https://blog.jetbrains.com/idea/feed/",
        concepts=("java", "kotlin"),
        display="IntelliJ IDEA blog feed",
        why="Official IntelliJ IDEA blog RSS",
    ),
    _rss_seed(
        slug="jetbrains-rust",
        name="RustRover",
        home="https://www.jetbrains.com/rust/",
        url="https://blog.jetbrains.com/rust/feed/",
        concepts=("rust",),
        display="RustRover blog feed",
        why="Official RustRover blog RSS",
    ),
    _rss_seed(
        slug="jetbrains-go",
        name="GoLand",
        home="https://www.jetbrains.com/go/",
        url="https://blog.jetbrains.com/go/feed/",
        concepts=("go",),
        display="GoLand blog feed",
        why="Official GoLand blog RSS",
    ),
    _rss_seed(
        slug="pypi",
        name="PyPI",
        home="https://pypi.org",
        url="https://pypi.org/rss/updates.xml",
        concepts=("pypi", "python"),
        display="PyPI package updates feed",
        why="Official PyPI package update RSS",
    ),
)

_SUBSCRIBE_FEED_FAMILIES = frozenset({SourceKind.RSS_ATOM, SourceKind.JSON_FEED})


def official_subscribe_seeds_for_topic(topic_name: str) -> tuple[SourceSeed, ...]:
    from app.services.user_interest import resolve_concept_id

    concept_id = resolve_concept_id(topic_name)
    return tuple(
        seed
        for seed in (*CURATED_SOURCE_SEEDS, *CURATED_SUBSCRIPTION_FEED_SEEDS)
        if concept_id in seed.concept_ids and seed.family in _SUBSCRIBE_FEED_FAMILIES
    )


def curated_subscribe_feed_urls() -> frozenset[str]:
    from app.services.source_registry import canonicalize_url

    urls: set[str] = set()
    for seed in (*CURATED_SOURCE_SEEDS, *CURATED_SUBSCRIPTION_FEED_SEEDS):
        if seed.family not in _SUBSCRIBE_FEED_FAMILIES:
            continue
        try:
            urls.add(canonicalize_url(seed.url))
        except ValueError:
            continue
    return frozenset(urls)


def is_curated_subscribe_feed_url(url: str) -> bool:
    from app.services.source_registry import canonicalize_url

    try:
        return canonicalize_url(url) in curated_subscribe_feed_urls()
    except ValueError:
        return False

