"""Curated seed registry for topic-driven source discovery.

Seeds are identity and ranking hints only. They never schedule fetches,
create subscriptions, or qualify as Claim evidence.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from app.services.source_catalog import SourceKind


class DiscoveryProvenance(StrEnum):
    CURATED_SEED = "curated_seed"
    REPOSITORY_METADATA = "repository_metadata"
    WEBSITE_FEED = "website_feed"
    STATUSPAGE_LINK = "statuspage_link"
    SITEMAP_LINK = "sitemap_link"
    PACKAGE_HOMEPAGE = "package_homepage"
    EXTERNAL_INDEX = "external_index"
    PUBLISHER_GRAPH = "publisher_graph"


@dataclass(frozen=True)
class SourceSeed:
    publisher_slug: str
    publisher_name: str
    homepage_url: str
    url: str
    family: SourceKind
    concept_ids: tuple[str, ...]
    provenance: str
    display_name: str
    why: str
    aliases: tuple[str, ...] = ()
    repository: str | None = None
    package: str | None = None


def _seed(
    *,
    slug: str,
    name: str,
    home: str,
    url: str,
    family: SourceKind,
    concepts: tuple[str, ...],
    provenance: str,
    display: str,
    why: str,
    aliases: tuple[str, ...] = (),
    repository: str | None = None,
    package: str | None = None,
) -> SourceSeed:
    return SourceSeed(
        publisher_slug=slug,
        publisher_name=name,
        homepage_url=home,
        url=url,
        family=family,
        concept_ids=concepts,
        provenance=provenance,
        display_name=display,
        why=why,
        aliases=aliases,
        repository=repository,
        package=package,
    )


CURATED_SOURCE_SEEDS: tuple[SourceSeed, ...] = (
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://github.com/facebook/react/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("react",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="React GitHub Releases",
        why="Official repository releases for React",
        aliases=("https://github.com/facebook/react",),
        repository="facebook/react",
    ),
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://react.dev/blog/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("react",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="React blog feed",
        why="Official React blog RSS",
    ),
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://react.dev/learn",
        family=SourceKind.GENERIC_WEB,
        concepts=("react",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="React documentation",
        why="Official React documentation",
    ),
    _seed(
        slug="llvm",
        name="LLVM",
        home="https://llvm.org",
        url="https://github.com/llvm/llvm-project/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("llvm", "llvm-scalar-evolution", "compiler-optimization"),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="LLVM project releases",
        why="Official LLVM repository releases",
        repository="llvm/llvm-project",
    ),
    _seed(
        slug="llvm",
        name="LLVM",
        home="https://llvm.org",
        url="https://llvm.org/docs/",
        family=SourceKind.GENERIC_WEB,
        concepts=("llvm", "llvm-scalar-evolution", "compiler-optimization"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="LLVM documentation",
        why="Official LLVM documentation, including Scalar Evolution",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://github.com/python/cpython/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("python",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="CPython releases",
        why="Official CPython repository releases",
        repository="python/cpython",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://blog.python.org/feeds/posts/default",
        family=SourceKind.RSS_ATOM,
        concepts=("python",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Python blog feed",
        why="Official Python blog Atom feed",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://docs.python.org/3/",
        family=SourceKind.GENERIC_WEB,
        concepts=("python",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Python documentation",
        why="Official Python language documentation",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://github.com/fastapi/fastapi/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="FastAPI releases",
        why="Official FastAPI repository releases",
        aliases=("https://github.com/encode/fastapi/releases",),
        repository="fastapi/fastapi",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://pypi.org/project/fastapi/",
        family=SourceKind.GENERIC_WEB,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.PACKAGE_HOMEPAGE,
        display="FastAPI on PyPI",
        why="Package registry homepage for FastAPI",
        package="fastapi",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://fastapi.tiangolo.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="FastAPI documentation",
        why="Official FastAPI documentation",
    ),
    _seed(
        slug="kubernetes",
        name="Kubernetes",
        home="https://kubernetes.io",
        url="https://github.com/kubernetes/kubernetes/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("kubernetes",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Kubernetes releases",
        why="Official Kubernetes repository releases",
        repository="kubernetes/kubernetes",
    ),
    _seed(
        slug="kubernetes",
        name="Kubernetes",
        home="https://kubernetes.io",
        url="https://kubernetes.io/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("kubernetes",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Kubernetes blog feed",
        why="Official Kubernetes website feed",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://github.blog/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("github", "github-actions"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="GitHub blog feed",
        why="Official GitHub blog RSS",
        aliases=("https://www.github.com",),
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://kctbh9vrtdwd.statuspage.io/api/v2/summary.json",
        family=SourceKind.STATUSPAGE,
        concepts=("github", "github-actions"),
        provenance=DiscoveryProvenance.STATUSPAGE_LINK,
        display="GitHub Statuspage",
        why="Known official GitHub Statuspage",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://api.github.com",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("github",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="GitHub Releases API",
        why="Official GitHub Releases API",
    ),
    _seed(
        slug="osv",
        name="OSV",
        home="https://osv.dev",
        url="https://api.osv.dev/v1/query",
        family=SourceKind.OSV,
        concepts=("oss_security", "security", "cve"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="OSV vulnerability API",
        why="Official OSV query API for security advisories",
    ),
    _seed(
        slug="cisa",
        name="CISA Cybersecurity Advisories",
        home="https://www.cisa.gov",
        url="https://www.cisa.gov/news-events/cybersecurity-advisories",
        family=SourceKind.GENERIC_WEB,
        concepts=("oss_security", "security", "cve"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="CISA Cybersecurity Advisories",
        why="Official CISA cybersecurity advisories",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://api.github.com/advisories",
        family=SourceKind.GITHUB_ADVISORY,
        concepts=("oss_security", "security", "cve", "github"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="GitHub Advisory Database",
        why="Official GitHub security advisories",
    ),
    _seed(
        slug="kotlin",
        name="Kotlin",
        home="https://kotlinlang.org",
        url="https://github.com/JetBrains/kotlin/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("kotlin",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Kotlin releases",
        why="Official Kotlin repository releases",
        repository="JetBrains/kotlin",
    ),
    _seed(
        slug="kotlin",
        name="Kotlin",
        home="https://kotlinlang.org",
        url="https://blog.jetbrains.com/kotlin/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("kotlin",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Kotlin blog feed",
        why="Official Kotlin blog RSS",
    ),
    _seed(
        slug="android",
        name="Android",
        home="https://developer.android.com",
        url="https://android-developers.googleblog.com/feeds/posts/default",
        family=SourceKind.RSS_ATOM,
        concepts=("android", "kotlin"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Android Developers blog feed",
        why="Official Android Developers blog feed",
    ),
    _seed(
        slug="android",
        name="Android",
        home="https://developer.android.com",
        url="https://developer.android.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("android",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Android developer documentation",
        why="Official Android developer documentation",
    ),
    _seed(
        slug="flutter",
        name="Flutter",
        home="https://flutter.dev",
        url="https://github.com/flutter/flutter/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("flutter",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Flutter releases",
        why="Official Flutter repository releases",
        repository="flutter/flutter",
    ),
    _seed(
        slug="flutter",
        name="Flutter",
        home="https://flutter.dev",
        url="https://blog.flutter.dev/feed",
        family=SourceKind.RSS_ATOM,
        concepts=("flutter",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Flutter blog feed",
        why="Official Flutter blog feed",
    ),
    _seed(
        slug="cloudflare-workers",
        name="Cloudflare Workers",
        home="https://developers.cloudflare.com/workers/",
        url="https://blog.cloudflare.com/rss/",
        family=SourceKind.RSS_ATOM,
        concepts=("cloudflare-workers", "cloudflare"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Cloudflare blog feed",
        why="Official Cloudflare blog RSS covering Workers",
    ),
    _seed(
        slug="cloudflare-workers",
        name="Cloudflare Workers",
        home="https://developers.cloudflare.com/workers/",
        url="https://developers.cloudflare.com/workers/",
        family=SourceKind.GENERIC_WEB,
        concepts=("cloudflare-workers", "cloudflare"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Cloudflare Workers documentation",
        why="Official Cloudflare Workers documentation",
    ),
    _seed(
        slug="openai",
        name="OpenAI",
        home="https://openai.com",
        url="https://openai.com/news/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("openai-api", "openai"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="OpenAI news feed",
        why="Official OpenAI news RSS",
    ),
    _seed(
        slug="openai",
        name="OpenAI",
        home="https://openai.com",
        url="https://platform.openai.com/docs",
        family=SourceKind.GENERIC_WEB,
        concepts=("openai-api",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="OpenAI API documentation",
        why="Official OpenAI API documentation",
    ),
    _seed(
        slug="nextjs",
        name="Next.js",
        home="https://nextjs.org",
        url="https://github.com/vercel/next.js/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("nextjs",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Next.js releases",
        why="Official Next.js repository releases",
        repository="vercel/next.js",
    ),
    _seed(
        slug="nextjs",
        name="Next.js",
        home="https://nextjs.org",
        url="https://nextjs.org/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("nextjs",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Next.js blog feed",
        why="Official Next.js blog RSS",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://github.com/rust-lang/rust/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("rust",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Rust releases",
        why="Official Rust repository releases",
        repository="rust-lang/rust",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://blog.rust-lang.org/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("rust",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Rust blog feed",
        why="Official Rust blog RSS",
    ),
    _seed(
        slug="hugo",
        name="Hugo",
        home="https://gohugo.io",
        url="https://gohugo.io/index.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("hugo",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Hugo docs feed",
        why="Official Hugo documentation RSS",
    ),
    _seed(
        slug="jekyll",
        name="Jekyll",
        home="https://jekyllrb.com",
        url="https://jekyllrb.com/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("jekyll",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Jekyll blog feed",
        why="Official Jekyll blog RSS",
    ),
    _seed(
        slug="ghost",
        name="Ghost",
        home="https://ghost.org",
        url="https://ghost.org/changelog/rss/",
        family=SourceKind.RSS_ATOM,
        concepts=("ghost",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Ghost changelog feed",
        why="Official Ghost changelog RSS",
    ),
    _seed(
        slug="vue",
        name="Vue",
        home="https://vuejs.org",
        url="https://blog.vuejs.org/feed.rss",
        family=SourceKind.RSS_ATOM,
        concepts=("vue",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Vue blog feed",
        why="Official Vue blog RSS",
    ),
    _seed(
        slug="vue",
        name="Vue",
        home="https://vuejs.org",
        url="https://vuejs.org/guide/introduction.html",
        family=SourceKind.GENERIC_WEB,
        concepts=("vue",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Vue documentation",
        why="Official Vue documentation",
    ),
    _seed(
        slug="angular",
        name="Angular",
        home="https://angular.dev",
        url="https://blog.angular.dev/feed",
        family=SourceKind.RSS_ATOM,
        concepts=("angular",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Angular blog feed",
        why="Official Angular blog feed",
    ),
    _seed(
        slug="typescript",
        name="TypeScript",
        home="https://www.typescriptlang.org",
        url="https://devblogs.microsoft.com/typescript/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("typescript",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="TypeScript blog feed",
        why="Official TypeScript blog RSS",
    ),
    _seed(
        slug="go",
        name="Go",
        home="https://go.dev",
        url="https://go.dev/blog/feed.atom",
        family=SourceKind.RSS_ATOM,
        concepts=("go",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Go blog feed",
        why="Official Go blog Atom feed",
    ),
    _seed(
        slug="go",
        name="Go",
        home="https://go.dev",
        url="https://go.dev/doc/",
        family=SourceKind.GENERIC_WEB,
        concepts=("go",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Go documentation",
        why="Official Go documentation",
    ),
    _seed(
        slug="ruby",
        name="Ruby",
        home="https://www.ruby-lang.org",
        url="https://www.ruby-lang.org/en/feeds/news.rss",
        family=SourceKind.RSS_ATOM,
        concepts=("ruby",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Ruby news feed",
        why="Official Ruby news RSS",
    ),
    _seed(
        slug="swift",
        name="Swift",
        home="https://www.swift.org",
        url="https://www.swift.org/atom.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("swift",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Swift blog feed",
        why="Official Swift Atom feed",
    ),
    _seed(
        slug="java",
        name="Java",
        home="https://openjdk.org",
        url="https://inside.java/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("java",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Inside Java feed",
        why="Official Inside Java RSS",
    ),
    _seed(
        slug="postgresql",
        name="PostgreSQL",
        home="https://www.postgresql.org",
        url="https://www.postgresql.org/news.rss",
        family=SourceKind.RSS_ATOM,
        concepts=("postgresql",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="PostgreSQL news feed",
        why="Official PostgreSQL news RSS",
    ),
    _seed(
        slug="redis",
        name="Redis",
        home="https://redis.io",
        url="https://redis.io/blog/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("redis",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Redis blog feed",
        why="Official Redis blog RSS",
    ),
    _seed(
        slug="deno",
        name="Deno",
        home="https://deno.com",
        url="https://deno.com/blog/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("deno",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Deno blog feed",
        why="Official Deno blog RSS",
    ),
    _seed(
        slug="neovim",
        name="Neovim",
        home="https://neovim.io",
        url="https://neovim.io/news.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("neovim",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Neovim news feed",
        why="Official Neovim news RSS",
    ),
    _seed(
        slug="linux",
        name="Linux kernel",
        home="https://www.kernel.org",
        url="https://www.kernel.org/category/releases.html",
        family=SourceKind.GENERIC_WEB,
        concepts=("linux",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Linux kernel releases",
        why="Official kernel release notes",
    ),
    _seed(
        slug="webassembly",
        name="WebAssembly",
        home="https://webassembly.org",
        url="https://webassembly.org/news/",
        family=SourceKind.GENERIC_WEB,
        concepts=("webassembly",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="WebAssembly news",
        why="Official WebAssembly news",
    ),
    _seed(
        slug="oss-security",
        name="oss-security",
        home="https://www.openwall.com/lists/oss-security/",
        url="https://www.openwall.com/lists/oss-security/",
        family=SourceKind.GENERIC_WEB,
        concepts=("oss_security", "security"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="oss-security list",
        why="Official oss-security mailing list archive",
    ),
    _seed(
        slug="react-native",
        name="Meta Native UI",
        home="https://react.dev",
        url="https://reactnative.dev/blog/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("react-native",),
        provenance=DiscoveryProvenance.PUBLISHER_GRAPH,
        display="Native UI blog feed",
        why="Official Meta-maintained native UI blog feed",
    ),
    _seed(
        slug="meta",
        name="Meta Engineering",
        home="https://react.dev",
        url="https://engineering.fb.com/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("react-native",),
        provenance=DiscoveryProvenance.PUBLISHER_GRAPH,
        display="Meta engineering feed",
        why="Corporate engineering feed from the frontend ecosystem",
    ),
    _seed(
        slug="vue",
        name="Vue",
        home="https://vuejs.org",
        url="https://blog.evanyou.me",
        family=SourceKind.GENERIC_WEB,
        concepts=("vue",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Evan You blog",
        why="Vue creator's development blog",
    ),
    _seed(
        slug="angular",
        name="Angular",
        home="https://angular.dev",
        url="https://blog.nrwl.io/feed",
        family=SourceKind.RSS_ATOM,
        concepts=("angular",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Nx engineering feed",
        why="Engineering feed maintained by the Angular ecosystem",
    ),
    _seed(
        slug="typescript",
        name="TypeScript",
        home="https://www.typescriptlang.org",
        url="https://www.totaltypescript.com/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("typescript",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Total TypeScript feed",
        why="TypeScript-focused developer feed",
    ),
    _seed(
        slug="typescript",
        name="TypeScript",
        home="https://www.typescriptlang.org",
        url="https://dev.to/t/typescript",
        family=SourceKind.GENERIC_WEB,
        concepts=("typescript",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="TypeScript community",
        why="TypeScript-tagged developer articles",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://aws.amazon.com/blogs/opensource/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("rust",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="AWS Open Source feed",
        why="Corporate open-source engineering feed covering Rust",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://this-week-in-rust.org/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("rust",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="This Week in Rust feed",
        why="Rust community news feed",
    ),
    _seed(
        slug="go",
        name="Go",
        home="https://go.dev",
        url="https://engineering.grab.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("go",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Grab engineering",
        why="Corporate engineering source with Go development",
    ),
    _seed(
        slug="go",
        name="Go",
        home="https://go.dev",
        url="https://dave.cheney.net/feed",
        family=SourceKind.RSS_ATOM,
        concepts=("go",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Dave Cheney feed",
        why="Go developer blog feed",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://realpython.com/atom.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("python",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Real Python feed",
        why="Python developer education feed",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://engineering.atspotify.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("python",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Spotify engineering",
        why="Corporate engineering source with Python development",
    ),
    _seed(
        slug="ruby",
        name="Ruby",
        home="https://www.ruby-lang.org",
        url="https://shopify.engineering/blog.atom",
        family=SourceKind.RSS_ATOM,
        concepts=("ruby",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Shopify engineering feed",
        why="Corporate engineering feed covering Ruby",
    ),
    _seed(
        slug="ruby",
        name="Ruby",
        home="https://www.ruby-lang.org",
        url="https://tenderlovemaking.com/atom.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("ruby",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Tenderlove feed",
        why="Ruby implementation developer blog feed",
    ),
    _seed(
        slug="kotlin",
        name="Kotlin",
        home="https://kotlinlang.org",
        url="https://blog.kotlin-academy.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("kotlin",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Kotlin Academy",
        why="Kotlin developer education source",
    ),
    _seed(
        slug="swift",
        name="Swift",
        home="https://www.swift.org",
        url="https://developer.apple.com/news/rss/news.rss",
        family=SourceKind.RSS_ATOM,
        concepts=("swift",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Apple developer news feed",
        why="Official Apple developer news feed",
    ),
    _seed(
        slug="java",
        name="Java",
        home="https://openjdk.org",
        url="https://spring.io/blog.atom",
        family=SourceKind.RSS_ATOM,
        concepts=("java",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Spring blog feed",
        why="Java ecosystem framework feed",
    ),
    _seed(
        slug="java",
        name="Java",
        home="https://openjdk.org",
        url="https://www.infoq.com/java/",
        family=SourceKind.GENERIC_WEB,
        concepts=("java",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="InfoQ Java",
        why="Java engineering news source",
    ),
    _seed(
        slug="llvm",
        name="LLVM",
        home="https://llvm.org",
        url="https://reviews.llvm.org",
        family=SourceKind.GENERIC_WEB,
        concepts=("llvm",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="LLVM reviews",
        why="Official LLVM review and development source",
    ),
    _seed(
        slug="android",
        name="Android",
        home="https://developer.android.com",
        url="https://medium.com/androiddevelopers",
        family=SourceKind.GENERIC_WEB,
        concepts=("android",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Android Developers community",
        why="Android Developers publication",
    ),
    _seed(
        slug="flutter",
        name="Flutter",
        home="https://flutter.dev",
        url="https://medium.com/flutter",
        family=SourceKind.GENERIC_WEB,
        concepts=("flutter",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Flutter community",
        why="Flutter developer publication",
    ),
    _seed(
        slug="kubernetes",
        name="Kubernetes",
        home="https://kubernetes.io",
        url="https://www.cncf.io/blog/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("kubernetes",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="CNCF blog feed",
        why="Cloud-native foundation feed covering Kubernetes",
    ),
    _seed(
        slug="linux",
        name="Linux",
        home="https://www.kernel.org",
        url="https://lwn.net/headlines/rss",
        family=SourceKind.RSS_ATOM,
        concepts=("linux",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="LWN headlines feed",
        why="Linux kernel and ecosystem news feed",
    ),
    _seed(
        slug="linux",
        name="Linux",
        home="https://www.kernel.org",
        url="https://lore.kernel.org",
        family=SourceKind.GENERIC_WEB,
        concepts=("linux",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Linux kernel mailing lists",
        why="Linux kernel development archive",
    ),
    _seed(
        slug="postgresql",
        name="PostgreSQL",
        home="https://www.postgresql.org",
        url="https://www.citusdata.com/blog/",
        family=SourceKind.GENERIC_WEB,
        concepts=("postgresql",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Citus Data blog",
        why="PostgreSQL engineering source",
    ),
    _seed(
        slug="postgresql",
        name="PostgreSQL",
        home="https://www.postgresql.org",
        url="https://www.depesz.com/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("postgresql",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="depesz PostgreSQL feed",
        why="PostgreSQL developer blog feed",
    ),
    _seed(
        slug="redis",
        name="Redis",
        home="https://redis.io",
        url="https://antirez.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("redis",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Redis creator blog",
        why="Redis creator's development source",
    ),
    _seed(
        slug="nextjs",
        name="Next.js",
        home="https://nextjs.org",
        url="https://vercel.com/blog/category/nextjs",
        family=SourceKind.GENERIC_WEB,
        concepts=("nextjs",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Vercel Next.js blog",
        why="Corporate Next.js engineering source",
    ),
    _seed(
        slug="deno",
        name="Deno",
        home="https://deno.com",
        url="https://kitsonkelly.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("deno",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Kitson Kelly blog",
        why="Deno ecosystem developer source",
    ),
    _seed(
        slug="cloudflare",
        name="Cloudflare",
        home="https://www.cloudflare.com",
        url="https://blog.cloudflare.com/tag/engineering",
        family=SourceKind.GENERIC_WEB,
        concepts=("cloudflare",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Cloudflare engineering",
        why="Official Cloudflare engineering articles",
    ),
    _seed(
        slug="webassembly",
        name="WebAssembly",
        home="https://webassembly.org",
        url="https://surma.dev/index.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("webassembly",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Surma feed",
        why="WebAssembly developer blog feed",
    ),
    _seed(
        slug="neovim",
        name="Neovim",
        home="https://neovim.io",
        url="https://tjdevries.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("neovim",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="TJ DeVries blog",
        why="Neovim maintainer developer source",
    ),
)
