"""Curated seed registry for topic-driven source discovery.

Seeds are identity and ranking hints only. They never schedule fetches,
create subscriptions, or qualify as Claim evidence.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from app.services.source_catalog import SourceKind


class DiscoveryProvenance(StrEnum):
    CURATED_SEED = "curated_seed"
    REPOSITORY_METADATA = "repository_metadata"
    WEBSITE_FEED = "website_feed"
    STATUSPAGE_LINK = "statuspage_link"
    SITEMAP_LINK = "sitemap_link"
    PACKAGE_HOMEPAGE = "package_homepage"
    EXTERNAL_INDEX = "external_index"


@dataclass(frozen=True)
class SourceSeed:
    publisher_slug: str
    publisher_name: str
    homepage_url: str
    url: str
    family: SourceKind
    concept_ids: tuple[str, ...]
    provenance: str
    display_name: str
    why: str
    aliases: tuple[str, ...] = ()
    repository: str | None = None
    package: str | None = None


def _seed(
    *,
    slug: str,
    name: str,
    home: str,
    url: str,
    family: SourceKind,
    concepts: tuple[str, ...],
    provenance: str,
    display: str,
    why: str,
    aliases: tuple[str, ...] = (),
    repository: str | None = None,
    package: str | None = None,
) -> SourceSeed:
    return SourceSeed(
        publisher_slug=slug,
        publisher_name=name,
        homepage_url=home,
        url=url,
        family=family,
        concept_ids=concepts,
        provenance=provenance,
        display_name=display,
        why=why,
        aliases=aliases,
        repository=repository,
        package=package,
    )


CURATED_SOURCE_SEEDS: tuple[SourceSeed, ...] = (
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://github.com/facebook/react/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("react",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="React GitHub Releases",
        why="Official repository releases for React",
        aliases=("https://github.com/facebook/react",),
        repository="facebook/react",
    ),
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://react.dev/blog/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("react",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="React blog feed",
        why="Official React blog RSS",
    ),
    _seed(
        slug="react",
        name="React",
        home="https://react.dev",
        url="https://react.dev/learn",
        family=SourceKind.GENERIC_WEB,
        concepts=("react",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="React documentation",
        why="Official React documentation",
    ),
    _seed(
        slug="llvm",
        name="LLVM",
        home="https://llvm.org",
        url="https://github.com/llvm/llvm-project/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("llvm", "llvm-scalar-evolution", "compiler-optimization"),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="LLVM project releases",
        why="Official LLVM repository releases",
        repository="llvm/llvm-project",
    ),
    _seed(
        slug="llvm",
        name="LLVM",
        home="https://llvm.org",
        url="https://llvm.org/docs/",
        family=SourceKind.GENERIC_WEB,
        concepts=("llvm", "llvm-scalar-evolution", "compiler-optimization"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="LLVM documentation",
        why="Official LLVM documentation, including Scalar Evolution",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://github.com/python/cpython/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("python",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="CPython releases",
        why="Official CPython repository releases",
        repository="python/cpython",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://blog.python.org/feeds/posts/default",
        family=SourceKind.RSS_ATOM,
        concepts=("python",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Python blog feed",
        why="Official Python blog Atom feed",
    ),
    _seed(
        slug="python",
        name="Python",
        home="https://www.python.org",
        url="https://docs.python.org/3/",
        family=SourceKind.GENERIC_WEB,
        concepts=("python",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Python documentation",
        why="Official Python language documentation",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://github.com/fastapi/fastapi/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="FastAPI releases",
        why="Official FastAPI repository releases",
        aliases=("https://github.com/encode/fastapi/releases",),
        repository="fastapi/fastapi",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://pypi.org/project/fastapi/",
        family=SourceKind.GENERIC_WEB,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.PACKAGE_HOMEPAGE,
        display="FastAPI on PyPI",
        why="Package registry homepage for FastAPI",
        package="fastapi",
    ),
    _seed(
        slug="fastapi",
        name="FastAPI",
        home="https://fastapi.tiangolo.com",
        url="https://fastapi.tiangolo.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("fastapi",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="FastAPI documentation",
        why="Official FastAPI documentation",
    ),
    _seed(
        slug="kubernetes",
        name="Kubernetes",
        home="https://kubernetes.io",
        url="https://github.com/kubernetes/kubernetes/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("kubernetes",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Kubernetes releases",
        why="Official Kubernetes repository releases",
        repository="kubernetes/kubernetes",
    ),
    _seed(
        slug="kubernetes",
        name="Kubernetes",
        home="https://kubernetes.io",
        url="https://kubernetes.io/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("kubernetes",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Kubernetes blog feed",
        why="Official Kubernetes website feed",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://github.blog/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("github", "github-actions"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="GitHub blog feed",
        why="Official GitHub blog RSS",
        aliases=("https://www.github.com",),
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://kctbh9vrtdwd.statuspage.io/api/v2/summary.json",
        family=SourceKind.STATUSPAGE,
        concepts=("github", "github-actions"),
        provenance=DiscoveryProvenance.STATUSPAGE_LINK,
        display="GitHub Statuspage",
        why="Known official GitHub Statuspage",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://api.github.com",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("github",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="GitHub Releases API",
        why="Official GitHub Releases API",
    ),
    _seed(
        slug="osv",
        name="OSV",
        home="https://osv.dev",
        url="https://api.osv.dev/v1/query",
        family=SourceKind.OSV,
        concepts=("security", "cve"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="OSV vulnerability API",
        why="Official OSV query API for security advisories",
    ),
    _seed(
        slug="github",
        name="GitHub",
        home="https://github.com",
        url="https://api.github.com/advisories",
        family=SourceKind.GITHUB_ADVISORY,
        concepts=("security", "cve", "github"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="GitHub Advisory Database",
        why="Official GitHub security advisories",
    ),
    _seed(
        slug="kotlin",
        name="Kotlin",
        home="https://kotlinlang.org",
        url="https://github.com/JetBrains/kotlin/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("kotlin",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Kotlin releases",
        why="Official Kotlin repository releases",
        repository="JetBrains/kotlin",
    ),
    _seed(
        slug="kotlin",
        name="Kotlin",
        home="https://kotlinlang.org",
        url="https://blog.jetbrains.com/kotlin/feed/",
        family=SourceKind.RSS_ATOM,
        concepts=("kotlin",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Kotlin blog feed",
        why="Official Kotlin blog RSS",
    ),
    _seed(
        slug="android",
        name="Android",
        home="https://developer.android.com",
        url="https://android-developers.googleblog.com/feeds/posts/default",
        family=SourceKind.RSS_ATOM,
        concepts=("android", "kotlin"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Android Developers blog feed",
        why="Official Android Developers blog feed",
    ),
    _seed(
        slug="android",
        name="Android",
        home="https://developer.android.com",
        url="https://developer.android.com",
        family=SourceKind.GENERIC_WEB,
        concepts=("android",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Android developer documentation",
        why="Official Android developer documentation",
    ),
    _seed(
        slug="flutter",
        name="Flutter",
        home="https://flutter.dev",
        url="https://github.com/flutter/flutter/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("flutter",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Flutter releases",
        why="Official Flutter repository releases",
        repository="flutter/flutter",
    ),
    _seed(
        slug="flutter",
        name="Flutter",
        home="https://flutter.dev",
        url="https://blog.flutter.dev/feed",
        family=SourceKind.RSS_ATOM,
        concepts=("flutter",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Flutter blog feed",
        why="Official Flutter blog feed",
    ),
    _seed(
        slug="cloudflare-workers",
        name="Cloudflare Workers",
        home="https://developers.cloudflare.com/workers/",
        url="https://blog.cloudflare.com/rss/",
        family=SourceKind.RSS_ATOM,
        concepts=("cloudflare-workers", "cloudflare"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Cloudflare blog feed",
        why="Official Cloudflare blog RSS covering Workers",
    ),
    _seed(
        slug="cloudflare-workers",
        name="Cloudflare Workers",
        home="https://developers.cloudflare.com/workers/",
        url="https://developers.cloudflare.com/workers/",
        family=SourceKind.GENERIC_WEB,
        concepts=("cloudflare-workers", "cloudflare"),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="Cloudflare Workers documentation",
        why="Official Cloudflare Workers documentation",
    ),
    _seed(
        slug="openai",
        name="OpenAI",
        home="https://openai.com",
        url="https://openai.com/news/rss.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("openai-api", "openai"),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="OpenAI news feed",
        why="Official OpenAI news RSS",
    ),
    _seed(
        slug="openai",
        name="OpenAI",
        home="https://openai.com",
        url="https://platform.openai.com/docs",
        family=SourceKind.GENERIC_WEB,
        concepts=("openai-api",),
        provenance=DiscoveryProvenance.CURATED_SEED,
        display="OpenAI API documentation",
        why="Official OpenAI API documentation",
    ),
    _seed(
        slug="nextjs",
        name="Next.js",
        home="https://nextjs.org",
        url="https://github.com/vercel/next.js/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("nextjs",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Next.js releases",
        why="Official Next.js repository releases",
        repository="vercel/next.js",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://github.com/rust-lang/rust/releases",
        family=SourceKind.GITHUB_RELEASE,
        concepts=("rust",),
        provenance=DiscoveryProvenance.REPOSITORY_METADATA,
        display="Rust releases",
        why="Official Rust repository releases",
        repository="rust-lang/rust",
    ),
    _seed(
        slug="rust",
        name="Rust",
        home="https://www.rust-lang.org",
        url="https://blog.rust-lang.org/feed.xml",
        family=SourceKind.RSS_ATOM,
        concepts=("rust",),
        provenance=DiscoveryProvenance.WEBSITE_FEED,
        display="Rust blog feed",
        why="Official Rust blog RSS",
    ),
)
